### ISSUE TITLE
Consider pulling the Citizen Code of Conduct (partially) to a rust-lang repository

### ISSUE THREAD

**Issue by skade** [rust-lang/core-team#17]
For a long time, our Code of Conduct used to link to citizencodeofconduct.org for a number of definitions. This page has become unavailable/spotty over the years. The link was recently replaced by a link to someones GH repository. (https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md) (1)
Particularly, our "harassment" definition relies on Citizen Code of Conduct:

> We will exclude you from interaction if you insult, demean or harass anyone. That is not welcome behavior. We interpret the term “harassment” as including the definition in the Citizen Code of Conduct; if you have any lack of clarity about what might be included in that concept, please read their definition. In particular, we don’t tolerate behavior that excludes people in socially marginalized groups.

The exact section isn't linked, I assume Section 4 is the one intended:

https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md#4-unacceptable-behavior

Our Code of Conduct uses no other part of the Citizen CoC.

There are two potential problems:
* Without us knowing, the definition may change without our knowledge. This is unlikely given the current state of the Citizen CoC, but has happened before. (For those historically interested: https://berlincodeofconduct.org/ comes from the same lineage, but uses their old clause in a different extension)
* If we ever feel like expanding/clarifying the harassment definition, we cannot do so easily, without approaching the Stumptown Syndicate.

As the definition remained stable since 2013, I would like to propose pulling the definition into our main document. We are also now a much larger project with people experienced in CoC writing plus the ability to fund external help, so I think deferring to another authority has outlived its usefulness.

The Rust Code of Conduct is nowadays used as a primary source, so having a complete document adds value.

This is a minor change, but as core maintains the CoC, I think a decision is needed.

(1) https://github.com/rust-lang/www.rust-lang.org/issues/1212

**Comment by Manishearth** [comment]
I'm in favor of doing this, I've never been fond of having an external link there as a hard dependency.

**Comment by skade** [comment]
Note by @pietroalbini: make sure we give appropriate credit to the original source.

**Comment by steveklabnik** [comment]
Everyone is still on board, just need to do the work.

**Comment by steveklabnik** [comment]
This week: just needs to be done

**Comment by skade** [comment]
https://gist.github.com/skade/273db8769d30164cbc407a4272d783f6

Proposed change: add an additional section and refer to it in the main text. Add the section between the main section and the Mod section.

**Comment by Manishearth** [comment]
nit: "within our community" isn't quite accurate, we take action on harassment outside the community too (harassment is the only item for which we do this)

**Comment by steveklabnik** [comment]
Triage: @skade not in attendance, but everyone is gonna check out the gist and comment.

**Comment by steveklabnik** [comment]
1. florian has the change made, will post

**Comment by steveklabnik** [comment]
Triage: @skade not in attendance

**Comment by steveklabnik** [comment]
No updates this week.

**Comment by skade** [comment]
PR open: https://github.com/rust-lang/www.rust-lang.org/pull/1287

**Comment by skade** [comment]
Closing here, as the PR is open and there's no further comments.
