### ISSUE TITLE
permissions on blog.rust-lang.org

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/core-team#18]
Currently the permissions on blog.rust-lang.org are a bit limited. What do people think about giving team (co-)leads permissions to enable them to post Inside Rust blog posts without needing "external" approval?

**Comment by nikomatsakis** [comment]
Discussed and agreed. For now, giving team leads permissions to merge makes sense, we can even limit those commits to the directory. ideally.

**Comment by steveklabnik** [comment]
People are generally in favor, especially for inside rust.

**Comment by emilyalbini** [comment]
Done!

**Comment by emilyalbini** [comment]
[A thing that was noted in the PR](https://github.com/rust-lang/blog.rust-lang.org/pull/670#pullrequestreview-467532015) is that project group leads don't have write access to the Inside Rust blog. That might be useful to post status updates from the project groups.

Do we want to grant them access? This will not include Domain Working Group leads.

**Comment by steveklabnik** [comment]
We are going to do this, @pietroalbini is gonna make it happen

**Comment by emilyalbini** [comment]
Opened https://github.com/rust-lang/blog.rust-lang.org/pull/682 to fix this.

**Comment by steveklabnik** [comment]
This has been merged!
