### ISSUE TITLE
Make prev.rust-lang.org archived and close all issues

### ISSUE THREAD

**Issue by skade** [rust-lang/core-team#21]
https://github.com/rust-lang/prev.rust-lang.org/ is still an active repository and sometimes, people use its issue tracker. As prev.rust-lang.org mainly exists for historical purposes and there's no intention to update it, I propose to archive the repository and close its issue tracker and all issues.

**Comment by Manishearth** [comment]
Update from triage: We should do this.

**Comment by Manishearth** [comment]
Done.
