### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/core-team#22]
Following Mozilla Legal recommendations, I posted a [PR updating our privacy policy](https://github.com/rust-lang/www.rust-lang.org/pull/1282), with the following changes:

**New section for crates.io:**

> Crates.io uses Sentry, an error monitoring service, to help the Rust team discover and fix the performance of the code. When there is an error, Sentry receives basic information about how you interacted with the website and the actions that led to the error. Additionally, your IP address may be disclosed to Sentry as part of the error reporting process but we’ve configured Sentry to delete it as soon as it’s received. Read <a href="https://sentry.io/privacy/">Sentry’s Privacy Policy here</a>.

**New section for docs.rs:**

> When you visit docs.rs, we receive your IP address and user-agent header as part of our standard server logs. We store these logs for 1 year.

Also, a disclaimer was added on top of all translated policies saying the English version is the canonical one.

We should decide whether to approve the privacy policy change.

**Comment by Manishearth** [comment]
Checkin from triage: We can go forward with this change, but filed https://github.com/rust-lang/core-team/issues/23 as a followup.

**Comment by emilyalbini** [comment]
Merged the changes! The new policy is here: https://www.rust-lang.org/policies/privacy
