### ISSUE TITLE
Figure out if we should be asking for T&C/Privacy Policy consent on crates.io

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/core-team#23]
Currently you can create an account on crates.io without explicitly consenting to any of the policies. Worth asking legal if this needs to be changed.

**Comment by emilyalbini** [comment]
No update here this week.

**Comment by nikomatsakis** [comment]
Update: I e-mailed Mozilla legal to ask whether we need to get folks to consent to changes and if/how we should notify them.

**Comment by emilyalbini** [comment]
We got advice from legal that we don't need to mass-communicate the change to users with the changes we made.

About getting consent when a user signs up for crates.io, we'll implement it along with #24.
