### ISSUE TITLE
Trademark request for void linux

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/core-team#4]
This issue is to log a trademark request from Void Linux, placed on January 3rd by @gottox. Key excerpts from the request follow:

> We're a small distribution that distributes a patched version of rust to
our users. These patches mostly fix issues with our musl-libc system and
some big-endian fixes. No features are added, changed, or removed. Is it
possible to use the cargo and rust trademarks for the package name?
>
> See [1] and [2] for a complete list of patches

Excerpt from my response from Jan 22:

> Speaking for Mozilla and the Rust core team, this looks like reasonable use and you should feel free to use the trademark in connection to refer to the Rust package on Void Linux.

[1]: https://github.com/void-linux/void-packages/tree/master/srcpkgs/rust/patches
[2]: https://github.com/void-linux/void-packages/tree/master/srcpkgs/rust/files/patches/static-llvm

**Comment by Gottox** [comment]
thank you :heart:
