### ISSUE TITLE
Target tier policy RFC

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/core-team#5]
We’re tracking [RFC 2803](https://github.com/rust-lang/rfcs/pull/2803), which sets policies for adding targets to the compiler and promoting them to higher tiers. The Core Team is interested in this RFC as it’s a priority for us to increase the amount of supported targets, and there are already multiple ones that would benefit from it shortly after being merged.

*Item added by before we transitioned to this issue tracker for our agenda.*

**Comment by nikomatsakis** [comment]
Update: @joshtriplett updated the RFC, but I at least haven't had time to read up on it yet. @pietroalbini left some notes. So: still progressing.

**Comment by emilyalbini** [comment]
No major update on this.

**Comment by steveklabnik** [comment]
No updates this week.

**Comment by steveklabnik** [comment]
No updates this week

**Comment by steveklabnik** [comment]
No updates this week

**Comment by steveklabnik** [comment]
No updates this week. We're not going to check in every week anymore; the original purpose was to make sure core is aware, but we're happy with the overall direction, the teams can take it from here.

**Comment by Mark-Simulacrum** [comment]
Josh has revised the RFC, and it contains a number of references to legal obligations for the Rust project not being "onerous" - I would like to clarify whether we want that determination to be made by lawyers or if we believe regular developers should be able to make it unless there are new cases to be checked (i.e. we would just accept a new target that has the same legal characteristics as a previous one). For cases where we would like to consult with lawyers, I would like to confirm that going through the core team is appropriate (though latency may be high and we may deem such requirement to exceed the benefits of the targets addition).
