### ISSUE TITLE
Rust Survey for 2020

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/core-team#7]
We're already in the second half of the year, and we should start thinking about the 2020 Rust Survey.

*Item added by @Mark-Simulacrum before we transitioned to this issue tracker for our agenda.*

**Comment by nikomatsakis** [comment]
Update: It's getting time to think about the Rust 2020 survey. @nikomatsakis will look into whether he can hire a contractor again this year to help with the data crunching, but there's plenty of other work to be done (such as assembling the questions, coordinating translations, etc), so we should get started on organizing that too.

**Comment by emilyalbini** [comment]
No major update, but a [Zulip stream was created](https://rust-lang.zulipchat.com/#narrow/stream/249854-t-community.2Frust-survey-2020) to chat about this.

**Comment by steveklabnik** [comment]
No updates this week

**Comment by steveklabnik** [comment]
No updates this week

**Comment by steveklabnik** [comment]
We're thinking about slimming the survey down this year; it's been growing every year and so is hard to process. It's not clear who is going to be doing that this year. Feels a bit ad-hoc this year and we should try to help smooth that out.

**Comment by steveklabnik** [comment]
we are on track to post the blog post next week to announce the survey. we still need some translators, but it's only been a couple of days.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/687

**Comment by steveklabnik** [comment]
Survey in progress!

**Comment by Manishearth** [comment]
Update from triage: stuff is going on, working on translating responses which may take a while.

**Comment by Manishearth** [comment]
Update from triage: Waiting on translations

**Comment by nikomatsakis** [comment]
Update: Translations are complete, starting to look at the data.

**Comment by steveklabnik** [comment]
Work is still ongoing.

**Comment by Mark-Simulacrum** [comment]
No major update. We are waiting on a sync up with core for the people running preliminary analysis.

**Comment by nikomatsakis** [comment]
Ryan and I did some discussion yesterday morning and highlighted various things we want to dig into, especially looking into the sorts of things that are blocked for people using Rust at work and so forth. Overall my personal impression was that the survey results look similar to prior years. For example, top priorities that people are concerned about (beyond the use at work):

* library ecosystem
* IDE support
* learning curve

**Comment by aidanhs** [comment]
Ryan says things are getting close to completion.

**Comment by aidanhs** [comment]
Niko says there's a draft blog post with the learnings from the survey, looking good, not yet a PR.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/736 is the draft and will be merged later today.
